---
title: "Plotly assignment"
author: "Jeff Dean, PhD"
date: "8/2/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plotly Post
```{r COVID_data, cache=FALSE, echo=FALSE, message=FALSE,warning=FALSE,}
library(rjson)
library(dplyr)

data_url <- 'https://covid19-lake.s3.us-east-2.amazonaws.com/enigma-jhu/csv/Enigma-JHU.csv.gz'
temp <- tempfile()
download.file(data_url, temp)
data <- read.csv(temp,colClasses = c("fips"="character"))  

data$country_region <- as.character(data$country_region)  # make region a character vector
us_data <- data[data$country_region=="US",]       # Downselect data to US
us_data <- us_data[us_data$fips!="",]             # drop rows where the fips value is missing
grouped <- us_data %>% group_by(combined_key)     # Group records by location name
deaths <- grouped %>% filter(deaths==max(deaths)) # Take the cumulative death value/city
by_county <- deaths %>% group_by(fips)            # Group records by county
sum_deaths <- by_county %>% summarise(tot_deaths = sum(deaths)) # get total deaths per county
temp <- ""; data <- ""; us_data <- ""; grouped <- ""; by_county <- ""; deaths <- ""
```

```{r do_plot, echo=FALSE, message=FALSE,warning=FALSE}
library(plotly)
library(rjson)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)
g <- list(scope='usa', projection=list(type='albers usa', showlakes=TRUE,
        lakecolor = plotly::toRGB('white')))
fig <- plotly::plot_ly(colorscale="Log")
fig <- fig %>% plotly::add_trace(
    type="choropleth",
    geojson=counties,
    locations=sum_deaths$fips,
    z=sum_deaths$tot_deaths+1, 
    zmin=0,
    zmax=200,
    text=deaths, 
    color="Viridis"
  )
fig <- fig %>% layout(title="Total US COVID-19 Deaths by County, March 2020")
fig <- fig %>% layout(geo = g)
fig
```


